image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script: yarn install --production=false
  artifacts:
    paths:
      - node_modules/
      - .yarn

build:
  stage: build
  before_script:
    - npm config set prefix /usr/local
    - npm install -g tsc
    - npm install -g serverless
  script: yarn build
  artifacts:
    paths:
      - .serverless/