service: api

plugins:
  - serverless-webpack
  - serverless-import-apigateway

custom:
  vpc:
    securityGroupIds:
      - 'Fn::ImportValue': ${env:STACK_NAME}-lambda-security-group
    subnetIds:
      - 'Fn::ImportValue': ${env:STACK_NAME}-lambda-subnet-1
      - 'Fn::ImportValue': ${env:STACK_NAME}-lambda-subnet-2
  importApiGateway:
    name: ${self:provider.stage}-common
    path: /
    resources:
      - /api

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ENVIRONMENT: ${env:ENVIRONMENT}
    NODE_ENV: ${env:NODE_ENV}

functions:
  ping:
    handler: src/handler/http.ping
    events:
      - http:
          method: get
          path: api/ping
